# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-15 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='attend_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='courseid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='is_present',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='studentid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='courseid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='is_active',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='qrid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='poll',
            name='qrstring',
            field=models.CharField(default=b' ', max_length=200),
        ),
    ]
