# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20160307_0424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='attend_id',
            new_name='qr_id',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='courseid',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='poll',
            name='qrid',
        ),
        migrations.AddField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='poll',
            name='created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
